### ISSUE TITLE
Update Angular core modules to 1.4.9 & then put a hard stop on updates until we upgrade to 2.0

### ISSUE THREAD

**Issue by jnmarcus** [caciviclab/disclosure-frontend#102]
1.5 was a large update with potentially breaking changes, so we should probably update now, and call it quits with Angular 1.**, until we upgrade to 2.0. 

Updates to other angular packages we'll have to watch and kind of play by ear.  As long as they don't break what we have, updating should be fine.  

It is actually possible for us to use Angular 2 in Angular 1 applications now tho, so if we have anyone that wants to dabble with Angular 2 before we officially upgrade, that could work.  I would say we should probably take that on a case by case basis, as we go.

**Comment by adborden** [comment]
We've had a few issues with newer package versions causing breakages. Angular is one of them. I think it's time to introduce a shrinkwrap file. Someone else had mentioned this before. Thoughts?

**Comment by jnmarcus** [comment]
@adborden my computer was wigging out every time I tried to run npm shrinkwrap, but the tests were passing, so I wanted to get this merged.  I created a new issue (#104) to shrinkwrap everything, feel free to take it.

**Comment by jnmarcus** [comment]
closed by #103
