### ISSUE TITLE
COMPONENT: Text Blurb 

### ISSUE THREAD

**Issue by amandaric** [caciviclab/disclosure-frontend#107]
A text blurb module is a section on the page that contains text. Example:

![2016-03-22_20-50-22](https://cloud.githubusercontent.com/assets/8173266/13975320/0b2cedfa-f071-11e5-941f-4dca2f42b69a.png)

The text blurb may contain the following sub-components:

- Title/Header
- Body copy
- Link to view/read more 

Possible interactions:

- Expandable: if the module includes a "read more" or "view more" text button, the module can expand
- Collapsible: once expanded, the module should have a link where users can collapse the module to the default size

**Comment by jnmarcus** [comment]
closed by #137
