### ISSUE TITLE
COMPONENT: Bar Chart

### ISSUE THREAD

**Issue by amandaric** [caciviclab/disclosure-frontend#111]
This chart will display amounts of money for or against a candidate or measure. Example:

![2016-03-29_21-06-02](https://cloud.githubusercontent.com/assets/8173266/14304472/d5d8da2c-fb67-11e5-9bbd-5d84f7b64d05.png)

The chart module includes:
- Title (i.e. "Within Oakland") is a bold dark gray font, sentence case, left-aligned
- Bar length illustrates fraction of a total; it can vary in length and should correspond to the percentage of total; bar color can vary based on information being depicted (i.e. contributors - green; opponents - red)
- Percentage of total (i.e. "56%") is bold light gray font placed immediately to the right of bar

**Comment by KyleW** [comment]
@elinaru Can you point me at the latest mock for this guy?

**Comment by KyleW** [comment]
Resolved by pull request #143
