### ISSUE TITLE
Remove 'develop' branch from workflow and work off of 'Master' instead

### ISSUE THREAD

**Issue by jnmarcus** [caciviclab/disclosure-frontend#120]

**Comment by KyleW** [comment]
I'll merge the open pull request to develop. then merge develop into master and delete develop once it's all approved.

**Comment by jnmarcus** [comment]
@KyleW sorry I didn't realize you had intended to finish this.  I just merged develop into master, changed the default branch to master, and deleted develop, so I'll close this issue for now

**Comment by KyleW** [comment]
works for me.
