### ISSUE TITLE
Glyphicons don't work

### ISSUE THREAD

**Issue by KyleW** [caciviclab/disclosure-frontend#135]
There's a bunch of error messages in the console around fonts and glyphicons don't work. We should iron out those kinks.

**Comment by KyleW** [comment]
@jnmarcus - Have you seen this too? Do you expect glyphicons to be available? I haven't investigated at all yet so I'm not even sure what it's supposed to be doing.

**Comment by jnmarcus** [comment]
@kyleW can you post a screenshot of the error messages you're seeing? And are you only seeing them on your computer? I'm not seeing it on the live site or on my local, so it's possible you just don't have the fonts installed on your machine

**Comment by KyleW** [comment]
This is what I'm seeing.
![screen shot 2016-08-03 at 8 33 34 pm](https://cloud.githubusercontent.com/assets/4153920/17389488/aa701804-59b9-11e6-80ab-6da16b700c91.png)

Notice the square next to "Read More" and the warrnings in the console:
ailed to decode downloaded font: http://localhost:5000/fonts/glyphicons-halflings-regular.woff2
:5000/#!/measure/1:1 OTS parsing error: invalid version tag
:5000/#!/measure/1:1 Failed to decode downloaded font: http://localhost:5000/fonts/glyphicons-halflings-regular.woff
:5000/#!/measure/1:1 OTS parsing error: invalid version tag
:5000/#!/measure/1:1 Failed to decode downloaded font: http://localhost:5000/fonts/glyphicons-halflings-regular.ttf
:5000/#!/measure/1:1 OTS parsing error: invalid version tag
:5000/#!/measure/1:1 Failed to decode downloaded font: http://localhost:5000/fonts/glyphicons-halflings-regular.woff2

Not sure what's up with that.

**Comment by KyleW** [comment]
Apparently, we're using font awesome instead. no issue here. Closing.
