### ISSUE TITLE
Update links on upcomingElectionList

### ISSUE THREAD

**Issue by KyleW** [caciviclab/disclosure-frontend#145]
Change links on the upcomingElectionList page from hrefs to ui-sref's and have them redirect to measure/:id/:locality and committee/:id/:locality instead of /:measure-name.

This will make it possible for users to test out more of the flows without having to manually enter urls.

**Comment by jnmarcus** [comment]
@KyleW does pull request #146 fix this issue or is there still more to do?

**Comment by KyleW** [comment]
Oh nice. you were already on it. At a quick glance, the answer is probably. I'm headed home shortly and will take a look.

sorry for the dupe issue.
