### ISSUE TITLE
Move Measure Summary Page into Referendum Page

### ISSUE THREAD

**Issue by jnmarcus** [caciviclab/disclosure-frontend#148]
[Invision desktop](https://projects.invisionapp.com/share/TK8O67TEZ#/screens/190014315)

Implement a two-column layout for the referendum page on desktop. Mobile retains the summary on a [separate page](https://projects.invisionapp.com/share/G58NM4GSR#/screens/190020313).

![screenshot from 2016-09-28 22-17-46](https://cloud.githubusercontent.com/assets/509703/18941858/6e37550a-85c9-11e6-9348-4f9fdb4773b2.png)

- [x] visualizations placed next to each other should use the same relative maximum as per usability test

**Comment by adborden** [comment]
Updated description.

**Comment by adborden** [comment]
Added a note about adjusting the maximum for side-by-side visualizations as per the usbaility test https://docs.google.com/document/d/1YRlgHC-Venn5oaTY7jrk42OJfabM8171EykkcHC1EQE/edit#

**Comment by adborden** [comment]
This is about combining [this page](http://www.opendisclosure.io/#!/city/2/oakland/2016/referendum/1/sugar-sweetened-beveragetax/supporting) and [this page](http://www.opendisclosure.io/#!/city/2/oakland/2016/referendum/1/sugar-sweetened-beveragetax) as per the mocks.

**Comment by adborden** [comment]
@anlawyer is currently working on this.

**Comment by adborden** [comment]
Done in https://github.com/caciviclab/odca-jekyll/pull/60
