### ISSUE TITLE
Update homepage based on updated mocks

### ISSUE THREAD

**Issue by jnmarcus** [caciviclab/disclosure-frontend#151]
Based on updated mocks (v.16): https://github.com/caciviclab/caciviclab.github.io/issues/14

- [ ] Add links to city pages from homepage
- [x] Add copy
- [x] Add background image
- [x] Include mobile and desktop designs

Related to #86

**Comment by adborden** [comment]
Fixed by https://github.com/caciviclab/disclosure-frontend/pull/161 left out the city links since we're only supporting Oakland for now.
