### ISSUE TITLE
Part 2: Add Office and Referendum Pages

### ISSUE THREAD

**Issue by jnmarcus** [caciviclab/disclosure-frontend#155]
Finish TODOs listed in #147 

note: based on updated designs (v.16) https://github.com/caciviclab/caciviclab.github.io/issues/14

**Comment by jnmarcus** [comment]
Related to #112

**Comment by adborden** [comment]
Copying todo's from #147 
- [ ] Add supporting and opposing charts to Referendum page (related to #112 and #144)
- [ ] Get dollarAmount for Office page
- [ ] Finish styling
- [ ] Review layout and desktop/mobile functionality with @elinaru and rest of team (although this may be better to do in a separate pull request)
- [ ] Review Office page functionality / layout with @elinaru and team (also could be done in separate pull request)

**Comment by adborden** [comment]
@KyleW I think the above are all done, or are better tracked in our UI hit list. Think we can close this?

**Comment by adborden** [comment]
ping @KyleW

**Comment by KyleW** [comment]
Yup. Closing.
