### ISSUE TITLE
Content for the ODCA About page

### ISSUE THREAD

**Issue by adborden** [caciviclab/disclosure-frontend#165]
http://disclosure.caciviclab.org/#!/about

@elinaru should we be using content from the mockups for this?

**Comment by sfdoran** [comment]
@elinaru Hope you don't mind I got something started based on the 2014 text with update on ODCA and characterizing this as beta-version with Oakland data.
https://docs.google.com/document/d/1OlIgIlY0bXbzgqIYmlNsz7aJ9_Kz7SzLbIJTdAyNGNg/edit

**Comment by adborden** [comment]
@elinaru incorporated the content into this draft https://docs.google.com/document/d/1kNFEu-sMsBVaAf6BZAquJhJDWeFMrp56dKJsHjN_3rc/edit#

**Comment by adborden** [comment]
Content is now live, :tada: http://www.opendisclosure.io/#!/about
