### ISSUE TITLE
Candidate photos are slow to load

### ISSUE THREAD

**Issue by adborden** [caciviclab/disclosure-frontend#179]
Especially on mobile, the candidate photos are slow to load. Some of them are Megabytes:

```
$ du -sh * | sort -h -r
9.8M    Jody-London2.jpg.JPG
6.9M    Huber-Trenado.jpg
536K    Jody-London.jpg
352K    F-Matt-Hummell.png
272K    Jody-London2.jpg.png
244K    Ben-Lang.png
232K    nancy-sidebotham2.png
216K    Barbara-Parker2.jpg
200K    F-Matt-Hummell.jpg
200K    dan-kalb2.png
192K    Marcie-Hodge.png
184K    Viola-Gonzales.png
168K    Huber-Trenado.png
160K    james-harris.png
148K    Lynette-Gibson-McElhaney.png
148K    Barbara-Parker.png
144K    Michael-Hassid.png
144K    Hinton-Hodge.png
124K    Noni-Session2.png
124K    Kevin-Corbett.png
112K    Noel-Gallo.png
104K    Patricia-Ellis.png
100K    Dan-Kalb.jpg
44K     Margaret-Moore.png
44K     Barbara-Parker.jpg
12K     James-Harris.jpg
```

@elinaru do you think you can optimize them further?

If not, maybe we should consider a thumbnail version for mobile.

**Comment by elinaru** [comment]
We're not using those larger images. They're in the folder because Phil has some sort of back-up thing happening where I can't delete them.

**Comment by evanwolf** [comment]
What can I do to change that?

**Comment by adborden** [comment]
Just for reference, [Peggy Moore's photo](https://s3-us-west-1.amazonaws.com/odca-candidate-photos/Margaret-Moore.png) is 300x300px and ~44K, one of the smallest. We should probably aim for this for all photos. We're not showing the photos are larger than 160px right now, so maybe we want to aim even smaller?

**Comment by adborden** [comment]
should we even bother with the 2016 photos? I suggest we close this.

**Comment by adborden** [comment]
Hearing nothing, closing.
