### ISSUE TITLE
Page banner to warn users when we are aware of a data correctness issue

### ISSUE THREAD

**Issue by adborden** [caciviclab/disclosure-frontend#187]
In the event someone points out an issue with the data, we'd like to put up a banner/other disclaimer letting the user know we're aware of an issue with the correctness of the data and are working on it. This doesn't need to be an overwhelming UI, but just something to show we're doing our due diligence.

Would be nice if we could also include a short description of the issue, so folks can still use the site for data that is correct.

cc @tdooner @elinaru

**Comment by elinaru** [comment]
See banner in mock-up here: https://invis.io/J48NM1DH2#/190014312_Desktop-Candidate-5-LocalList-Details

**Comment by adborden** [comment]
Some styling work was done in https://github.com/caciviclab/disclosure-frontend/pull/223

**Comment by adborden** [comment]
Done in https://github.com/caciviclab/odca-jekyll/pull/49
