### ISSUE TITLE
Add Google Analytics

### ISSUE THREAD

**Issue by adborden** [caciviclab/disclosure-frontend#199]
@tdooner should we use the existing GA account from the 2014 Open Disclosure site?

**Comment by KyleW** [comment]
Does anyone have the ga account credentials?

**Comment by tdooner** [comment]
Here's the embed code:

```js
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-50973042-1', 'auto');
  ga('send', 'pageview');
```

**Comment by KyleW** [comment]
Sweet. Thanks.

**Comment by tdooner** [comment]
🆒 Also, you should still have access from last time. Let me know if you've changed your email or need another invite or something.

**Comment by KyleW** [comment]
Yeah, I've still got it. Looks like I could have solved this problem
myself. Sorry about the noise.
