### ISSUE TITLE
Add "spent" and "raised" labels for ballot measure numbers

### ISSUE THREAD

**Issue by tdooner** [caciviclab/disclosure-frontend#202]
The numbers are inconsistent due to the discrepancy in how we calculate the contributions vs expenditures.

**Comment by adborden** [comment]
@tdooner this is related to this page, right? http://www.opendisclosure.io/#!/city/2/oakland/2016/referendum/1/sugar-sweetened-beveragetax/supporting

![screenshot from 2016-09-29 20-29-20](https://cloud.githubusercontent.com/assets/509703/18979853/7082f9da-8683-11e6-91b3-2098b3948947.png)

So the committee list is referring to expenditures and the sum total is referring to contributions, right?
