### ISSUE TITLE
Write short definitions for "non-itemized contributions" and "independent expenditure committees"

### ISSUE THREAD

**Issue by sseiter** [caciviclab/disclosure-frontend#21]
Everyone write a super short definition that we can use in the hover environment.

**Comment by tdooner** [comment]
@sseiter where is the document of plain english descriptions that we have been curating? Can you paste a link here so the person working on this issue can just add it there?

**Comment by bayreporta** [comment]
I can't find the link to that spreadsheet with all the terms, but my two cents:

"non-itemized contributions" = small contributions

"independent expenditure committees" = outside money groups (industry standard)

"independent expenditure" = outside money (industry standard)

Any others?

**Comment by elinaru** [comment]
Can we specify that "non-itemized contributions" are contributions under $100?

**Comment by evanwolf** [comment]
@bayreporta  https://docs.google.com/spreadsheets/d/1UKoSsBIh79tDSbG-gV6WczWpunOhOEkPopb16eHPYKY/edit?usp=sharing is the glossary table. 

I did some more work on the table this afternoon.

**Comment by evanwolf** [comment]
"non-itemized contributions" are under-$100 cash or in-kind contributions reported by a campaign. Unlike in-kind contributions, they are reported as a group without individually listing the transaction or the contributor. The exception to the under-$100 rule is if you give multiple times and the cumulative value is $200 or more; then the campaign will itemize and report each of your contributions.

**Comment by bcipolli** [comment]
@evanwolf very cool. @andrell81 do you have time to check out the doc above?

**Comment by adborden** [comment]
Can we keep these terms on the [Glossary Wiki](https://github.com/caciviclab/caciviclab.github.io/wiki/Glossary), rather than in a doc?

**Comment by adborden** [comment]
@sseiter can you confirm that all these "disclaimer" related issues are required before the PEC meeting? (I believe they are).

**Comment by adborden** [comment]
I believe @sfdoran might also be working on this?

**Comment by sfdoran** [comment]
@adborden There are entries in the text we've been working on under "FAQ" here: https://docs.google.com/document/d/14jrPU4leMUYtqgRZNhhU4Bi0552E3b9ZNrEwOUQ6e7c/edit?usp=sharing
