### ISSUE TITLE
Contributor tables on mobile display excessively truncates and obscures data

### ISSUE THREAD

**Issue by elinaru** [caciviclab/disclosure-frontend#229]
Here are the tables on my phone: 
![screenshot_2016-10-10-22-25-39](https://cloud.githubusercontent.com/assets/6467815/19259786/7c1c9242-8f39-11e6-8778-8d9f8f312c75.png)
![screenshot_2016-10-05-09-44-06](https://cloud.githubusercontent.com/assets/6467815/19259787/7c24e15e-8f39-11e6-9a06-cd8aad0ba063.png)

**Comment by elinaru** [comment]
Can we add some min-widths to these columns and search bar?

**Comment by KyleW** [comment]
We can and that's probably the easiest fix, but just to be clear that's going to make the grid wider than the screen. It won't cause cells to wrap to the next row.

**Comment by KyleW** [comment]
Mostly closed by #233. There's still some funkiness in the way the border shows up on the header row, but the basic usability problem is solved. I'll find some other place to note the display bug.
