### ISSUE TITLE
Add expenditures opposing candidates

### ISSUE THREAD

**Issue by mikeubell** [caciviclab/disclosure-frontend#231]
The backend is now providing opposing_money for candidates and a list of opposing money for committees.
The front end should display this.

**Comment by adborden** [comment]
The backend work is implemented in https://github.com/caciviclab/disclosure-backend-static/pull/60 (not yet merged).

This shows up as a single number
```javascript
candidate.opposing_money.opposing_expenditures: 12800
```

@elinaru not sure if there was a mockup for this that we cut. Here are some similar screens we could base this on
![screenshot from 2016-10-11 23-41-05](https://cloud.githubusercontent.com/assets/509703/19299972/4c1fe6ba-900c-11e6-8549-839da65e8de3.png)
![screenshot from 2016-10-11 23-40-48](https://cloud.githubusercontent.com/assets/509703/19299978/520f37ce-900c-11e6-9e21-8bf7a5f99afb.png)

**Comment by mikeubell** [comment]
Not sure where that number comes from.  The new code calculates opposing money for each candidate and a list of money spent against them.

**Comment by KyleW** [comment]
@mikeubell  I don't see the list of contributors in the main candidate response. Is there a different filer id that corresponds to contributions opposing a candidate?

**Comment by mikeubell** [comment]
There is a list of expenditures by opposing organizations off of the committee.  In the case of Kalb its here: build/committee/1382408/opposing/index.json

Not sure what the end point is in the server
