### ISSUE TITLE
Feedback: a question on data correctness

### ISSUE THREAD

**Issue by sfdoran** [caciviclab/disclosure-frontend#236]
Missing data for contributions and expenditures against Measure KK.

Found "Coalition to Improve Oakland Government - NO on Measure KK sponsored by Oakland small business and property owners, home owners and renters" filer id 1391606 and added to google sheet.

It's a general purpose recipient committee.

NetFile shows contributions on 10/27 pre-election 460 Schedule A and $10,724 expenditures on Schedule E plus $15,933 expenditures reported Schedule G and eleven 497s totaling $36,500 in contributions.

There is no data in the ballot measure or support/oppose fields or records under Schedule D - filer error?

Any chance we can fix it by tonight?

**Comment by tdooner** [comment]
@sfdoran If I understand correctly, you just added the filer to the google sheet, so it should just take a re-run of the processing to show them? I'll make sure to get this when I go home tonight.

**Comment by mikeubell** [comment]
I might be able to look.  I’m doing tech support at the Hillary phone bank so it might not happen.  Perhaps we just need to do a new build?  Tom can you try that?

**Comment by mikeubell** [comment]
Ah great minds think alike.

**Comment by tdooner** [comment]
Okay, I re-ran the data (locally -- I can't deploy it until I get home tonight) and it came up with this diff:

```diff
diff --git a/build/referendum/4/opposing/index.json b/build/referendum/4/opposing/index.json
index e9e46e9..ba26236 100644
--- a/build/referendum/4/opposing/index.json
+++ b/build/referendum/4/opposing/index.json
@@ -6,12 +6,22 @@
   "summary": "This measure would allow the City to borrow up to $600 million by issuing general obligation bonds. The bonds would be repaid with revenue from an “ad valorem” property tax. “Ad valorem” means according to the value of the property. The City would impose a tax based on the value of real property and improvements within the City to pay the principal and interest of the bonds. The City would use this money to build, buy, improve, and rehabilitate facilities and infrastructure and for affordable housing in Oakland. The projects financed by the bonds would be completed as needed according to City Council established priorities as set forth in the City’s Capital Improvement Plan.",
   "number": "KK",
   "opposing_organizations": [
-
-  ],
-  "total_contributions": [
-
+    {
+      "id": "1391606",
+      "name": "Coalition to Improve Oakland Government - NO on Measure KK sponsored by Oakland small business and property owners, home owners and renters",
+      "payee": "Coalition to Improve Oakland Government - NO on Measure KK sponsored by Oakland small business and property owners, home owners and renters",
+      "amount": 10724.12
+    }
   ],
+  "total_contributions": 36500.0,
   "contributions_by_region": [
-
+    {
+      "amount": 19500.0,
+      "locale": "Within California"
+    },
+    {
+      "amount": 17000.0,
+      "locale": "Within Oakland"
+    }
   ]
 }
```

Glad that it aligns with Suzanne's calculations on the first go. I'll push this to the site ASAP when I get home tonight.

**Comment by sfdoran** [comment]
I looked up this filer's 460 and it did indicate opposition to KK - I am following up with the City Clerk and NetFile to find out why it doesn't show up that way in our data.

**Comment by adborden** [comment]
@sfdoran is this still an issue?

**Comment by adborden** [comment]
Closing, we can re-open if needed.
