### ISSUE TITLE
James Harris showing $114,769 Not Stated but Expenses shows only $17,322

### ISSUE THREAD

**Issue by adborden** [caciviclab/disclosure-frontend#246]
![screenshot from 2017-01-17 20-22-10](https://cloud.githubusercontent.com/assets/509703/22050784/adbcde5e-dcf2-11e6-874f-deb00b12eb4c.png)
![screenshot from 2017-01-17 20-21-59](https://cloud.githubusercontent.com/assets/509703/22050785/b2a4ee52-dcf2-11e6-9645-86be64c62e43.png)

cc @sfdoran

**Comment by sfdoran** [comment]
This looks to me like the independent expenditures reported by FAMILIES AND EDUCATORS FOR PUBLIC EDUCATION, SPONSORED BY GO PUBLIC SCHOOLS ADVOCATES. They reported $153,309.51 spent in support of Harris, mostly in independent expenditures. Approx $114K was reported on Form 496s (Late Independent Expenditures). "Expn_Dscr" shows the description in the Form 496 data. 

You can see the same pattern with the other school board candidates supported by Families and Educators.

Adding IE spending in with the candidate's spending is confusing. You can't tell that the money is coming from another committee or what committee it is. It would be better to show it as its own item.

**Comment by mikeubell** [comment]
@tdooner Why are we including 497 information as expenditures for candidates as this form (p2) only records contributions?  So this would be a contribution from IEC to a candidate not an expenditure for or by the candidate. @sfdoran do I have this right?

**Comment by mikeubell** [comment]
This is fixed in the backend now.  we have separated out IEC supporting actions into "supporting_by_type" which should be displayed separately.  Also fixed the missing "opposing_by_type" data which needs to be displayed.

**Comment by mikeubell** [comment]
Fixed in backend
