### ISSUE TITLE
Deploy frontend to our actual server

### ISSUE THREAD

**Issue by tdooner** [caciviclab/disclosure-frontend#32]
Deploying to our real server (instead of GH pages) is pretty important so we can support dynamic URLs.

This issue tracks the work necessary to actually deploy the frontend to our disclosure.caciviclab.org server.

**Comment by KyleW** [comment]
Are we still relying on gh pages? If so, this seems important. @tdooner  I'm glad to do this work, but would need to know where to put it and may need additional permissions to make dns work right.

**Comment by tdooner** [comment]
@KyleW I think we got around this through some other frontend method, though I forget exactly what that was. At least for now, using URL fragments will allow us to not have to do this ticket yet.

**Comment by jnmarcus** [comment]
@KyleW we are still relying on gh pages. @tdooner are u saying that because we're using Angular UI-Router we don't need to do this? (just making sure I understand)

**Comment by KyleW** [comment]
I'm glad to explore the topic either way. I know very little (errr . . . nothing) about gh pages, but I'll read the docs and figure it out. I can't imagine that's where we expect this to live perpetuity right?
