### ISSUE TITLE
Rename this repo to `disclosure-frontend`

### ISSUE THREAD

**Issue by tdooner** [caciviclab/disclosure-frontend#33]
Although this is still in alpha mode, it seems unlikely to me that we'll need to differentiate between multiple disclosure-frontend repos given that this one is where all the work is currently happening.

**Comment by tdooner** [comment]
Thoughts, @jnmarcus ?

**Comment by adborden** [comment]
@tdooner @jnmarcus since it's the frontend for disclosure, I think `disclosure.caciviclab.io` makes more sense.

**Comment by tdooner** [comment]
I'm cool with that too - it's the "alpha" in the current name that bugs me.

**Comment by jnmarcus** [comment]
I'm fine with removing the "alpha".  Since we have so many repos, I feel like maybe we should keep the word "frontend" in it somewhere, just so that it's easier to understand what's what.

**Comment by bcipolli** [comment]
@tdooner Is there anything from stopping us from changing this? It's so easy to change in the settings, and github redirects URLs from the old name to the new.

**Comment by bcipolli** [comment]
Done.
