### ISSUE TITLE
Committee contributors component

### ISSUE THREAD

**Issue by adborden** [caciviclab/disclosure-frontend#47]
[Invision screen desktop](https://projects.invisionapp.com/share/TK8O67TEZ#/screens/190014307)
 
There is no invision screen for mobile.

The committee contributors page lists out individual contributors to a single committee. The focus is on searching and filtering contributors.

This is a placeholder story that sets up the page scaffolding so that we can break it into smaller pieces and have a shared foundation to work off of It should include:

- A route
- Page template
- Mock data
- Basic styling

This page will live at `/committee/:committee_id/contributors`

**Comment by evanwolf** [comment]
Do you imagine the name of a contributor to be clickable, leading to a contributor's page that lists their contributions (over time and to various recipients)?

**Comment by adborden** [comment]
Not for this version, but I think it would be useful to note during user testing whether or not folks want to drill down even further than this. It's already pretty dense for mobile.

**Comment by adborden** [comment]
@KyleW can you comment on this? I think this is effectively done or no longer relevant. I believe this corresponds to the committee page you called out in the OD spreadsheet and is completed by https://github.com/caciviclab/disclosure-frontend/pull/147

**Comment by KyleW** [comment]
I think I was wrong in the spreadsheet. I'll double check, but I believe the final 3 pieces are the candidates page, the committee page and the contributors page. Basically the 3 pages deepest into the flow. The components exist. They just need to be stitched together.

**Comment by adborden** [comment]
:thumbsup: is someone working on this? Can we assign someone? I'm leaving this as "in progress" unless no one is actually working on it.

**Comment by adborden** [comment]
On second thought I'm going to move this to Ready, it's not really "in progress" if no one is owning it. (and I have a hunch that someone is, just not sure who).

**Comment by adborden** [comment]
I updated the description here. We're not looking for a placeholder page anymore, we can start building the entire thing. We might want to break this story up, or at least ship it in multiple pull requests. So we can get some basic functionality out first, then the advanced stuff. We can also get this on committee pages first, then candidate pages.

I removed the `ready` label because I would like a [little more discussion](https://github.com/caciviclab/disclosure-backend-static/issues/20#issuecomment-248195096) happening.

**Comment by adborden** [comment]
@KyleW sounds like you're working on this?

**Comment by KyleW** [comment]
yes. This is actually the only committee component the backend expects to support. It should replace the other committee page tickets.

**Comment by KyleW** [comment]
Closed by #209 .
