### ISSUE TITLE
Refactor pages into components

### ISSUE THREAD

**Issue by adborden** [caciviclab/disclosure-frontend#62]
As per feedback from #45 and offline discussion, each page should live under `appMain`. The page will be a thin module, containing the ui-router state declaration and a controller to attach the state resolvers to the scope. The bulk of each page will exist as a directive under `common`, and the page will simply pass the data objects to directives.

cc @jnmarcus

**Comment by adborden** [comment]
Additionally, the components should be pretty flat. Even related components, such as the ballot measure page, ballot measure supporters, and ballot measure opposers, will not be nested in the directory hierarchy, but exist at the top-level under `common`.

**Comment by bcipolli** [comment]
Is there any more to do here, or done?

**Comment by adborden** [comment]
@jnmarcus can you comment on this one? I think it's complete, as written at least.

**Comment by adborden** [comment]
Ping @KyleW @jnmarcus, can you comment on this? I believe this was done a while ago and has since been refactored even further. I think we can close this now?

**Comment by KyleW** [comment]
Yeah, I think this is done. I'm going to close it. If I'm wrong, we can reopen later.
