### ISSUE TITLE
Homepage: when portal size is small, footer covers search box, with no scrollbars

### ISSUE THREAD

**Issue by bcipolli** [caciviclab/disclosure-frontend#69]
Can't get to the search box when the window size is small:
![image](https://cloud.githubusercontent.com/assets/4072455/12370479/54503fac-bbc7-11e5-898d-7eb8118eee0c.png)

**Comment by bcipolli** [comment]
Turns out that the footer will float to the bottom of the portal... even if there's a scrollbar.

**Comment by jnmarcus** [comment]
@bcipolli what's your expectation on the homepage for the behavior of the footer and the scrollbar?

also, how tall was your browser window when you shot this? (ish).  It looks about 300px high, in which case I would say that that use case may not be large (mobile phone heights start at 640px, so you wouldn't see this problem).  

Essentially, we can fix it, but what will happen is it will sit right below the search bar, always, and there will be grey space underneath.  See the screenshot attached:


<img width="1396" alt="screen shot 2016-02-24 at 8 35 10 pm" src="https://cloud.githubusercontent.com/assets/1439922/13309933/35038ddc-db36-11e5-9420-cca49a571611.png">

**Comment by adborden** [comment]
Let's add a minimum height to the homepage, plus some padding to account for the footer so we're never in this situation. I think [your comment](https://github.com/caciviclab/disclosure-frontend/issues/87#issuecomment-188614002) about how the homepage works compared to other pages is correct and we should keep that behavior.

**Comment by adborden** [comment]
This is fixed by the new footer design.

**Comment by adborden** [comment]
Fixed by https://github.com/caciviclab/disclosure-frontend/pull/161
