### ISSUE TITLE
Write "About Us" for CCL site

### ISSUE THREAD

**Issue by elinaru** [caciviclab/disclosure-frontend#7]
2014 Oakland OD About Us: http://www.opendisclosure.io/about

**Comment by elinaru** [comment]
Actually, using our Knight Foundation grant proposal text might be closer: https://www.newschallenge.org/challenge/elections/entries/open-disclosure-california-connecting-people-to-their-local-campaign-finance-data

**Comment by adborden** [comment]
This is what I had used for another page. Might be useful as a starting point, and I think was based on the proposal.

> California Civic Lab is a coalition of Code For America Brigades working to improve accessibility of local campaign finance data to ordinary voters across jurisdictions in California. Currently, campaign finance data is tied up in various forms, only eight percent of these jurisdictions provide this data in machine-readable digital form. For seventy-nine percent of California jurisdictions, forms are only available on request in paper form. We're hoping to change that.

**Comment by evanwolf** [comment]
potential elements of the _About Us_ page: 
- We're a coalition of volunteers. (the blurb)
- About Open Data, Transparency, and Better Government
- Our first project: OpenDisclosure
-- links and screenshot
-- purpose 
-- roadmap
-- a very brief history
- Member organizations. (list of CACLabs brigades, and delegates)
- Team members we'd like to thank (list of credited volunteers)
- N ways to help your community (get on your city's mailing list, ask your council for open data, join a brigade, share what you find, etc.)
- Colophon (list of tools we used, orgs that helped out, music we listened to, etc.)
- Our Policies 
-- Licenses
-- Download Our Data, Fork Our Code 
-- ToS (site, APIs)
-- Privacy 
- Stay informed (we'll never give or sell your email)

**Comment by elinaru** [comment]
I think we should separate this out into two tickets: an "About Us" page for the CCL site and an "About This Project" page for the ODCA.

**Comment by elinaru** [comment]
Opened https://github.com/caciviclab/disclosure-frontend-alpha/issues/16

**Comment by adborden** [comment]
+1 to keeping the pages distinct.

**Comment by tdooner** [comment]
This should be done in the caciviclab.github.io repo.

**Comment by bcipolli** [comment]
@tdooner Now that this project is a bit broader than the caciviclab, does it make sense to do this in this codebase directly?

**Comment by elinaru** [comment]
Opened https://github.com/caciviclab/caciviclab.github.io/issues/13 in the right repo. Closing this.
