### ISSUE TITLE
Move mock data from front-end to back-end 

### ISSUE THREAD

**Issue by bcipolli** [caciviclab/disclosure-frontend#73]
Currently, a number of URLs have `resolve` functions that don't access the back-end, but instead return a data object directly.

This issue is to simply move those data objects to the back-end, and access them through the `disclosure` service.

**Comment by bcipolli** [comment]
back-end was merged, now just need to connect the front-end.

**Comment by adborden** [comment]
@bcipolli I think this is done, yeah?

**Comment by bcipolli** [comment]
yep!
