### ISSUE TITLE
C3 directives

### ISSUE THREAD

**Issue by bcipolli** [caciviclab/disclosure-frontend#84]
Originally opened by @adborden at https://github.com/caciviclab/disclosure-backend/issues/31

>Angular directives for the C3 visualizations. @ajmobidesign anything to add?

**Comment by adborden** [comment]
@ajmobidesign you still working on this? @MrMaksimize might be able to help.

I can also help get C3 on the page if you're having issues with npm/browserify.

**Comment by jnmarcus** [comment]
c3-angular is now loaded into the project, so I'll close this for now.  Components aren't built for it yet, but it exists.  It is referenced at the top of `app.js`.
