### ISSUE TITLE
Desktop layout interim solution

### ISSUE THREAD

**Issue by adborden** [caciviclab/disclosure-frontend#86]
The pages look really janky on desktop. http://disclosure.caciviclab.org/#!/committee/1 Let's just come up with an interim solution. We're not using any of the bootstrap grid on the main app. Even making the sections 1/2 or 1/3 width would be a little better.

If we could get a final desktop design, that would be even better :)

cc @elinaru @sseiter

**Comment by bcipolli** [comment]
I must be showing my East Coast origins... I had to look up [janky](https://www.urbandictionary.com/define.php?term=janky) :smile_cat:

**Comment by adborden** [comment]
I grew up in NJ....

**Comment by bcipolli** [comment]
Eh... throw me a bone @adborden ! :wink:

**Comment by tdooner** [comment]
@adborden I think you meant "hella janky"

**Comment by adborden** [comment]
On Wed, 2016-01-27 at 22:50 -0800, Tom Dooner wrote:
> @adborden I think you meant "hella janky"

:D

-- 
Aaron D Borden
Human and Hacker

**Comment by elinaru** [comment]
Working on mock-ups for this now --

**Comment by adborden** [comment]
We are looking good on desktop https://projects.invisionapp.com/share/TK8O67TEZ#/screens/190014301

I think we can close this, right @elinaru ?
