### ISSUE TITLE
Frontend visual defects

### ISSUE THREAD

**Issue by adborden** [caciviclab/disclosure-frontend#87]
We're keeping  a list of the minor defects in the UI. We're not ready to create individual issues for these because we anticipate many many of them. Once we do one more QA pass for the frontend, then we'll say it's "good enough" and open individual issues when we find things that aren't "good enough".

- [ ] ["More details" link](http://disclosure.caciviclab.org/#!/committee/1) doesn't look good. Use font awesome.
- [ ] ~~[Footer](http://disclosure.caciviclab.org/#!/about) should be stick to the bottom of the window.~~
- [x] [Home page search](http://disclosure.caciviclab.org/#!/) results need styling.
- [x] [Demo Links](http://disclosure.caciviclab.org/#!/) header should be hidden on desktop.

**Comment by adborden** [comment]
I think @davidgarber started on this, can I assign it to you?

**Comment by jnmarcus** [comment]
@adborden @bcipolli what's your expectations for the footer's behavior across the site? 

Currently it is stuck to the bottom of the window on the homepage, but is flexible on its location based on the assumption that other content will be filling the page (which will in turn push the footer down to the bottom).  Fixing the footer to the bottom on pages that aren't the homepage, will limit the extents of the height of the page.  Basically content below the height of the window would fall _under_ (and behind) the footer that would be stuck to the end of the page.  see below: 

<img width="1389" alt="screen shot 2016-02-24 at 8 45 19 pm" src="https://cloud.githubusercontent.com/assets/1439922/13310060/a9988aa2-db37-11e5-8808-071687444fb2.png">

This is also related to #69 .  Whatever you guys prefer, we can change it tho.

**Comment by adborden** [comment]
Yeah, let's assume for the footer that the content will fill out the page a little more. We can come back to it once that page has some content. I'm removing it from the list.

**Comment by adborden** [comment]
The items in the list are complete, and the "more details" link doesn't exist anymore, so closing this.
