### ISSUE TITLE
Use search to discover SFO city ID for navbar

### ISSUE THREAD

**Issue by bcipolli** [caciviclab/disclosure-frontend#97]
Currently it's hard-coded to `71`. It would be a better demo (i.e. work when pointing to any backend server instance), and very instructive, if we got that ID by using the `localityApi.search` method to get the San Francisco id.

@adborden or @jnmarcus is this something you could set up easily? I could run with it a bit if so. Thanks!

**Comment by adborden** [comment]
On Thu, 2016-02-11 at 07:13 -0800, Ben Cipollini <notifications@github.com> wrote:
> Currently it's hard-coded to `71`. It would be a better demo (i.e. work when pointing to any backend server instance), and very instructive, if we got that ID by using the `localityApi.search` method to get the San Francisco id.
> 
> @adborden or @jnmarcus is this something you could set up easily? I could run with it a bit if so. Thanks!

@bcipolli can you include your repro steps? I think the frontend is all
wired up correctly, the issue is the backend stubs return id 71, so
that's what the frontend uses to query the rest of the data. No?

**Comment by bcipolli** [comment]
@adborden I was referring to this line of code: https://github.com/caciviclab/disclosure-frontend/blob/22c6f839c6be18ed67b910fb3c698359ae75eef9/app/components/common/appMainNav/appMainNavController.js#L38

**Comment by adborden** [comment]
I see. I guess it's not clear enough, but those links are "demo links", quick shortcuts to get to the different pages for demo and testing purposes. They should be removed before v1.0.

AFAIK [we don't have any definition](https://github.com/caciviclab/disclosure-frontend/issues/9) of what should be in the nav, so I propose we just remove the nav before version 1.0 unless we come up with something.

**Comment by adborden** [comment]
Created https://github.com/caciviclab/disclosure-frontend/issues/101 to track it.

@bcipolli can we close this? The search should work to get what you want.

**Comment by bcipolli** [comment]
Right. Those links don't work when I run set things up locally, which is why opened the issue. But no biggie--I'm mostly focused on data cleaning these days, so if it's not affecting others, no prob!
